In [101]:
import pandas as pd

# 讀取 Excel 文件中的兩個工作表
df1 = pd.read_excel(r'C:\Users\Hcedu\Downloads\DATA_test.xlsx', sheet_name=0)
df2 = pd.read_excel(r'C:\Users\Hcedu\Downloads\DATA_test.xlsx', sheet_name=1)

# # 查看 df1 和 df2 的列名和數據類型
# print("df1.info():")
# print(df1.info())
# print("df2.info():")
# print(df2.info())     #date    916 non-null    datetime64[ns]

# 確保 'date' 列是 datetime 格式
df1['date'] = pd.to_datetime(df1['date'])

# pd.merge 根據共同的 'login' 和 'date' 列
df= pd.merge(df1, df2, on=['login', 'date'], how='inner')

# df1['group'] == 'Test' #bool
# df1[df1['group'] == 'Test'] #535 Test	
# df1[df1['group'] == 'Test'].index #Index([535, 536, 537, 538, 
df = df.drop(df[df['group'] == 'Test'].index)

# 根據 'deposit' 列的值來設置 'bonus' 列
df['bonus'] = [1 if n > 3000 else 0 for n in df['deposit']]

# 根據日期範圍進行過濾
df = df[df['date'] <= '2021-03-05']
# 排序  # 非分配排名df.rank
df = df.sort_values(by='pnl', ascending=False)

df = df[['date','sales','pnl','volume','commission','deposit','bonus']]
df.head(20)

# # 將提取的 DataFrame 輸出到 Excel 文件
# output_file_path = r'C:\Users\Hcedu\Downloads\filtered_data.xlsx'
# df.to_excel(output_file_path, index=False)
# print(f"Data has been written to {output_file_path}")

,date,sales,pnl,volume,commission,deposit,bonus
296,2021-03-05,Chris Lizhuang,4031.249506,1.310115,-76.9146,0.000000,0
155,2021-03-03,Sally Liuyuntao ECN,3172.672928,0.696990,-29.5380,2133.560974,0
149,2021-03-03,Adel Nour,2799.796126,0.000000,0.0000,790.207764,0
213,2021-03-04,Adel Nour,2358.367540,0.546062,0.0000,0.000000,0
291,2021-03-05,Chris Lizhuang,2018.359282,0.612781,-36.6079,0.000000,0
246,2021-03-04,Chris Lizhuang,1936.027787,0.864358,-48.2160,7104.515137,1
276,2021-03-05,Chris Lizhuang,1899.193867,0.568117,-33.9524,0.000000,0
265,2021-03-04,Damon Gaoyu,1570.113672,2.660099,0.0000,0.000000,0
44,2021-03-01,Chris Lizhuang,1370.878838,0.886140,-46.8324,0.000000,0
86,2021-03-02,Sally Liuyuntao ECN,1348.708027,0.573005,-21.6179,0.000000,0
189,2021-03-03,Damon Gaoyu ECN,1338.530287,0.962826,-37.9300,0.000000,0
239,2021-03-04,Chris Lizhuang,989.603726,0.517779,-26.4288,0.000000,0
219,2021-03-04,Chris Lizhuang,952.802337,0.399262,-22.1187,0.000000,0
146,2021-03-03,Chris Lizhuang,935.348898,0.000000,0.0000,0.000000,0
145,2021-03-03,Adel Nour,858.872290,0.240283,0.0000,0.000000,0
288,2021-03-05,Chris Lizhuang,763.850470,0.228079,-13.6568,2370.979248,0
244,2021-03-04,Damon Gaoyu ECN,741.979792,0.479205,-15.6299,0.000000,0
36,2021-03-01,Chris Lizhuang,711.342734,0.382522,-22.1113,0.000000,0
14,2021-03-01,Chris Lizhuang,697.795984,0.353613,-20.4506,0.000000,0
7,2021-03-01,Chris Lizhuang,534.744684,0.000000,0.0000,0.000000,0

In [96]:
import pandas as pd

# Define the sample DataFrame
sample_df = pd.DataFrame({
    "sub": [50, 51, 52, 53, 54, 55, 56],
    "parent": [54, 55, 54, 56, 51, 0, 0]
})
# print(sample_df.info())

def find_ancestor_chain(df, sub):
    '''[topmost,level]   #print(find_ancestor_chain.__doc__) '''
    chain = []
    current = sub
    while True:
        chain.append(current)
        parent = df[df['sub'] == current]['parent'].values[0]
        if parent == 0 or parent == current:
            break
        current = parent
    # Find the top-most ancestor
    top_most_ancestor = max(chain)
    return [top_most_ancestor, len(chain) - 1]

# Example 
print(find_ancestor_chain(sample_df, 55))  # Output: [55, 0]
print(find_ancestor_chain(sample_df, 53))  # Output: [55, 3]

[55, 0]
[56, 1]